### ISSUE TITLE
Improve `lake` info and add control attribute to model

### ISSUE THREAD

**Issue by silveryfu** [digi-project/digi#39]
**Is your feature request related to a problem? Please describe.**

Enhancing `lake` digi's reported pool information.

**Describe the solution you'd like**

After #20, the `lake` meta digi now reports pool information on its model, e.g.,

```
pools:
  103f9306925a46d485a2b3a54a7ef4d3c5b55113:
    head: 0x103f935fd56e139a805fb9220eeac3884b94b0e6
    last_updated: 2023-01-01 19:37:42.135799+00:00
    size: 7
stats:
  num_pools: 1
```

We should make them more informative. Proposing a few enhancements:
- The polling interval could be a control attribute: https://github.com/digi-project/digi/blob/efccea18ccf203ce8358f0a8579d188eb92665a4/lake/driver/handler.py#L10 that the dSpace operator/user can tune with `digi edit`.
- Shall we use the pool's name as the identifier/key under `pools` attribute? Otherwise it's difficult to tell which pool is which. We can then store the pool id in a separate attribute (e.g., `pool_id`).
- When starting the `lake` instance, there should be initial values to some of the attributes, e.g., `stats` should report `num_pools` as 0. Currently the model is not populated until the first app digi is created.
Plus additional features others may have.
